from pathlib import Path
import os
import shutil
import subprocess
import sys
ROOT = Path(__file__).resolve().parents[1]
errors=[]
tools=['mise','uv','node','pnpm','make']
if os.environ.get('TEMPLATE_INFRA_MANAGED')!='1': tools.append('docker')
for name in tools:
    path=shutil.which(name)
    print(f'{name}: {path or "MISSING"}')
    if path is None: errors.append(name)
if sys.version_info[:2] != (3,13): errors.append('Python must be 3.13; run through mise exec')
if shutil.which('node'):
    node=subprocess.check_output(['node','-p','process.versions.node'],text=True).strip()
    print('Node:',node)
    if node.split('.')[0]!='24': errors.append('Node must be 24; run through mise exec')
if 'docker' in tools and shutil.which('docker'):
    result=subprocess.run(['docker','info','--format','{{.ServerVersion}}'],capture_output=True,text=True)
    print('Docker daemon:',result.stdout.strip() if result.returncode==0 else 'unavailable')
    if result.returncode: errors.append('Start Docker Desktop / grant access to the Docker daemon')
for relative in ['backend/uv.lock','frontend/pnpm-lock.yaml','frontend/src/generated/api.ts']:
    print(relative, 'present' if (ROOT/relative).exists() else 'generated by make install')
if errors: raise SystemExit('Prerequisites missing: '+', '.join(errors))
print('PASS: required tools and Docker daemon available.')
