import type { ReportingWorkspaceResponse } from '@/generated/models';
import { useQuery } from '@tanstack/react-query';

import { apiClient } from '@/shared/api/client';
import { apiConfig } from '@/shared/api/config';
import { toApiContractError } from '@/shared/api/errors';

import { getMockReportingCopilotSnapshot } from './mock';
import type { ReportingCopilotSnapshot, WorkspaceSelection } from './contracts';

type ApiSnapshot = ReportingWorkspaceResponse;
type Payload = Record<string, unknown>;
const record = (value: unknown): Payload =>
  value !== null && typeof value === 'object' && !Array.isArray(value)
    ? (value as Payload)
    : {};
const items = (value: unknown): Payload[] =>
  Array.isArray(value) ? value.map(record) : [];
const text = (value: unknown, fallback = '—') =>
  typeof value === 'string' || typeof value === 'number' ? String(value) : fallback;
const reportStatus = (
  value: unknown,
): 'DRAFT' | 'REVIEW' | 'APPROVED' | 'PUBLISHED' => {
  const status = text(value).toUpperCase();
  return status === 'DRAFT' ||
    status === 'REVIEW' ||
    status === 'APPROVED' ||
    status === 'PUBLISHED'
    ? status
    : 'DRAFT';
};

export function mapReportingSnapshot(snapshot: ApiSnapshot): ReportingCopilotSnapshot {
  const active = record(snapshot.active_report);
  return {
    contractStatus: 'LIVE_API_CONNECTED',
    copilotLifecycle: 'COPILOT_CONTRACT_PENDING',
    context: {
      companyId: snapshot.context.company_id,
      companyLabel: snapshot.context.company_label,
      periodId: snapshot.context.period_id,
      periodLabel: snapshot.context.period_label,
      scenarioId: snapshot.context.scenario_id,
      scenarioLabel: snapshot.context.scenario_label,
      asOf: snapshot.as_of,
    },
    reporting: {
      activeReport: {
        id: text(active.report_id),
        title: text(active.title, 'No published report'),
        template: text(active.template),
        reportingDate: text(active.reporting_date),
        status: reportStatus(active.status),
        currentVersionId: text(active.current_version_id),
        reviewer: 'Backend workflow',
        approver: 'Backend workflow',
        completeness: text(active.completeness, '—'),
        sourceCoverage: text(active.source_coverage, '—'),
        unresolvedFindings: items(snapshot.findings).length,
      },
      sections: items(snapshot.sections).map((section) => ({
        id: text(section.id),
        title: text(section.title),
        purpose: 'Published backend report section',
        owner: 'Reporting workflow',
        status: ['EMPTY', 'GENERATED', 'REVIEWED', 'APPROVED'].includes(
          text(section.status),
        )
          ? (text(section.status) as 'EMPTY' | 'GENERATED' | 'REVIEWED' | 'APPROVED')
          : 'GENERATED',
        sourceCount: Number(section.source_count ?? 0),
        wordCount: 0,
        materiality: 'HIGH',
      })),
      versions: items(snapshot.versions).map((version) => ({
        id: text(version.version_id),
        label: text(version.version_id),
        createdAt: snapshot.as_of,
        createdBy: 'Backend projection',
        status: reportStatus(version.status),
        sourceSnapshotIds: Array.isArray(version.source_snapshot_ids)
          ? version.source_snapshot_ids.map(String)
          : [],
        modelRunIds: [],
        checksum: text(version.content_hash),
      })),
      sourcePack: items(snapshot.source_pack).map((source) => ({
        id: text(source.source_id),
        type: 'SNAPSHOT',
        label: text(source.label),
        status: text(source.status) === 'APPROVED' ? 'VALIDATED' : 'STALE',
        asOf: text(source.as_of),
        owner: 'Data governance',
      })),
      exportTargets: items(snapshot.export_targets).map((target) => ({
        id: text(target.format),
        label: `${text(target.format)} export`,
        format: text(target.format) === 'PDF' ? 'PDF' : 'XLSX',
        status: text(target.status) === 'READY' ? 'READY' : 'BLOCKED',
        note: 'Generated by the backend export service',
      })),
      narrativePreview: [],
      findings: items(snapshot.findings).map((finding) => ({
        id: text(finding.finding_id),
        severity: 'MEDIUM',
        section: text(finding.section_id),
        finding: text(finding.message),
        owner: 'Reporting workflow',
        status: text(finding.status) === 'RESOLVED' ? 'RESOLVED' : 'OPEN',
      })),
    },
    copilot: {
      sessionId: 'not-available',
      groundingMode: 'VALIDATED_SOURCES_ONLY',
      contextSources: [],
      routes: [],
      messages: [],
      suggestedPrompts: [],
      proposedActions: [],
      guardrails: [
        {
          id: 'copilot-pending',
          label: 'Copilot contract',
          status: 'PENDING',
          detail: 'Release 6 owns the governed Copilot API.',
        },
      ],
    },
  };
}

export async function getReportingCopilotSnapshot(
  selection: WorkspaceSelection,
): Promise<ReportingCopilotSnapshot> {
  if (apiConfig.mode === 'mock' || import.meta.env.MODE === 'test')
    return getMockReportingCopilotSnapshot(selection);
  const { data, error, response } = await apiClient.GET('/api/v1/reporting/workspace', {
    params: {
      query: {
        company_id: selection.companyId,
        period_id: selection.periodId,
        scenario_id: selection.scenarioId,
      },
    },
  } as never);
  if (!data) throw toApiContractError(response, error);
  return mapReportingSnapshot(data as ApiSnapshot);
}

export function useReportingCopilotSnapshot(selection: WorkspaceSelection) {
  return useQuery({
    queryKey: [
      'reporting-copilot',
      selection.companyId,
      selection.periodId,
      selection.scenarioId,
    ],
    queryFn: () => getReportingCopilotSnapshot(selection),
    staleTime: apiConfig.mode === 'live' ? 30_000 : Number.POSITIVE_INFINITY,
    retry: apiConfig.mode === 'live' ? 1 : false,
  });
}
